#!/bin/sh

# abort on error
set -e

cd ~/src/neovim
git pull
make clean
make CMAKE_BUILD_TYPE=Release CMAKE_INSTALL_PREFIX=$HOME/.local/
make install

cd ~/src/neovim-qt
git pull
rm -r build
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/.local ..
cmake --build . --target install

