#!/bin/sh
while true
do
    url=$(curl --connect-timeout 1 --silent 192.168.0.44:8080)
    if [ -n "$url" -a "$url" != "$oldurl" ]
    then
        echo $url
        #firefox $url
        oldurl=$url
    fi
    sleep 1
done

